export default {
  defaultIgnores: true,
  ignores: [
    (commit) =>
      commit.includes(
        "This PR was generated by [Mend Renovate](https://mend.io/renovate/).",
      ),
  ],
  plugins: ["@gimoji/gimoji"],
  rules: {
    "body-max-line-length": [2, "always", 74],
    "header-max-length": [2, "always", 72],
    "start-with-gimoji": [2, "always"],
  },
};
